[package]

name = "bson"
version = "0.1.0"
authors = [ "Durran Jordan <durran@gmail.com>" ]

[lib]

name = "bson"
path = "src/lib.rs"

[dependencies]

byteorder = "^1.0.0"
linked-hash-map = "^0.4.0"

[dev-dependencies]

stainless = "^0.1.10"
expectest = "^0.6.0"
